CREATE DATABASE IF NOT EXISTS rl_ebgi_gs; 
 CREATE DATABASE IF NOT EXISTS rl_enty_def; 
 CREATE DATABASE IF NOT EXISTS rl_isis_is; 
 CREATE DATABASE IF NOT EXISTS rl_ebli_def; 
 CREATE DATABASE IF NOT EXISTS rl_wbcs_def; 
 CREATE DATABASE IF NOT EXISTS rl_imed_def; 
 